{{- with .Values.ue }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    app: {{ $.Values.projectName }}
    component: {{ .name }}
data:
  ue-config.yaml: |
    {{- .configuration | nindent 4 }}

{{- end }}
{{- end }}
