{{- with .Values.gnb }}
{{- if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    app: {{ $.Values.projectName }}
    component: {{ .name }}
data:
  gnb.yaml: |
    {{- .configuration | nindent 4 }}

{{- end }}
{{- end }}
